### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by JeremyBradshaw7** [kevinresol/react-native-sound-recorder#16]
Getting this on starting to record an mp4 file on Android device.

setAudioSource failed.
setAudioSource
    MediaRecorder.java
start
    RNSoundRecorderModule.java:108
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:790
dispatchMessage
    Handler.java:99
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:164
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:764

**Comment by godinfo** [comment]
same error here.

**Comment by kevinresol** [comment]
Closing due to lack of information
