### ISSUE TITLE
path

### ISSUE THREAD

**Issue by ctrljs** [kevinresol/react-native-sound-recorder#21]

**Comment by ctrljs** [comment]
Hi Kevin ,

How can i give my own path in the recording option, and can i get file size of the file being created ?

**Comment by ctrljs** [comment]
if (Platform.OS === 'android') {
      options['format'] = SoundRecorder.FORMAT_MPEG_4;
      options['encoder'] = SoundRecorder.ENCODER_AAC;
    }

also if use the above options , do i need to mention extension in the filename in the path supplied

**Comment by kevinresol** [comment]
> i give my own path in the recording option

please read the readme

> get file size of the file being created

you can use other libraries to query the file size

**Comment by ctrljs** [comment]
> > i give my own path in the recording option
> 
> please read the readme
> 
> > get file size of the file being created
> 
> you can use other libraries to query the file size

Can you share me a snippet of own filepath usage for android, 

My file is getting created properly  using your SoundRecorder.PATH_CACHE path and i am able to play it too. But I not able to locate it on phone file manager to get the file size.

Also
"   console.log('stopped recording, audio file saved at: ' + result.path); "

 I tried uploading to s3, passing the result.path , it say file doesnt exist at that location

**Comment by ctrljs** [comment]
done!!

**Comment by omkar-asort** [comment]
@ctrljs How did you solve this issue. Please help.

**Comment by ghost** [comment]
> done!!

would be useful to provide the code used

**Comment by kevinresol** [comment]
> I tried uploading to s3, passing the result.path , it say file doesnt exist at that location

Not a particular issue of this library, but whenever you use a path to locate a local file, you need to pay attention if the `file://` prefix is required to be present or absent. This varies from library to library, please consult the respective documentation.
