### ISSUE TITLE
how can i get the full path

### ISSUE THREAD

**Issue by chinavane** [kevinresol/react-native-sound-recorder#26]
result.path return path like /data/user/0/XXXXX，but i want to get the path like file:///storage/emulated/0/Pictures/images/image-0b1ae10a-d598-4f6d-aba5-f3212c4dd10f.jpg,whether to directly add the string file://

**Comment by kevinresol** [comment]
It is returning the full path already.

**Comment by omkar-asort** [comment]
@chinavane just prepend the path with "file://". This will give you the uri that you require.
