### ISSUE TITLE
Recording works in simulator, but not on device!

### ISSUE THREAD

**Issue by iMagdy** [kevinresol/react-native-sound-recorder#3]
When I record on simulator, it works fine, but when running on device, the file is empty. Any idea?

Running iOS.

**Comment by iMagdy** [comment]
Issue after debugging happens in `[session setActive:NO error:&err];` in particular. Any idea @kevinresol ?

**Comment by kevinresol** [comment]
What is the error?

**Comment by iMagdy** [comment]
Error returning in promise rejection is an empty object. How do I log it in xcode?

**Comment by kevinresol** [comment]
`NSLog`

**Comment by iMagdy** [comment]
`Error Domain=NSOSStatusErrorDomain Code=560030580 "(null)"`
  
This happens on stop, as an error for `session_set_active_error`

**Comment by iMagdy** [comment]
Found this here https://osstatus.com/search/results?platform=all&framework=all&search=560030580 if it may help.

**Comment by kevinresol** [comment]
In your JS, the promise returned by `start()` resolves no error while `stop()` resolves an error? Is it?

If `start()` already produces an error maybe we should investigate it first.

**Comment by iMagdy** [comment]
Start works fine, the problem is only with stop.

**Comment by kevinresol** [comment]
Whoops, you got the solution?
