### ISSUE TITLE
Unnecessary READ and WRITE permissions

### ISSUE THREAD

**Issue by kayzenkayzen** [kevinresol/react-native-sound-recorder#37]
I am seeing that depending on the directory that is being used to save the file, it is not always necessary to have read and write permissions.

For example if we are saved in PATH_CACHE ( getCacheDir() )

This says the Android documentation:

Apps require no extra permissions to read or write to the returned path since this path lives in their private storage.

**Comment by kevinresol** [comment]
Does this lib even request any permissions?

**Comment by irothenbaum** [comment]
Yes, it does request permissions (confirmed on Android). And I can confirm that with microphone permissions allowed, and using PATH_CACHE, it still requests file storage.

**Comment by kayzenkayzen** [comment]
> Does this lib even request any permissions?

Since the last release, yes!

**Comment by kevinresol** [comment]
Perhaps we should revert #28. I prefer requesting permissions manually in js (e.g. with react-native-permissions)

**Comment by kayzenkayzen** [comment]
I think it would be better to let the developer ask for the necessary permissions according to their recording configuration.

**Comment by kevinresol** [comment]
It had been my intention from the beginning. It was my mistake to merge #28.

**Comment by kevinresol** [comment]
Can anyone PR a fix?

**Comment by kevinresol** [comment]
f6c33b7a1bfbaa2d32b26ca0abf868f3c729df85
