### ISSUE TITLE
setAudioSource failed

### ISSUE THREAD

**Issue by tirthasourav** [kevinresol/react-native-sound-recorder#45]
![Screenshot 2020-07-30 at 1 07 26 PM](https://user-images.githubusercontent.com/24516153/88894575-b1847800-d265-11ea-8636-b9d421beded1.png)
Using react native 0.63.0. Getting 'setAudioSource failed' issue on android on Start recording

**Comment by upsilon-dev** [comment]
Just experienced the same issue but resolved it after adding requesting for runtime permissions.
https://reactnativecode.com/react-native-runtime-permissionsandroid/

**Comment by kevinresol** [comment]
Assume missing permission. Closing.

**Comment by mohammad6vakili** [comment]
You need to check the `RECORD_AUDIO` permission before start recording.

```
try {
      const grants = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
      );
      console.log('record audio', grants);
      if (grants === PermissionsAndroid.RESULTS.GRANTED) {
        SoundRecorder.start(SoundRecorder.PATH_CACHE + '/test.mp4').then(
          function () {
            console.log('started recording');
          },
        );
      } else {
         console.log('All required permissions not granted')
        return;
      }
    } catch (err) {
      console.warn(err);
      return;
    }
```
