### ISSUE TITLE
Pause Recording

### ISSUE THREAD

**Issue by rohitsainiidsil** [kevinresol/react-native-sound-recorder#47]
I am using this library and looking for Pause Recording and Resume Recording feature. Is this library support these features ?

**Comment by kevinresol** [comment]
Come on please read the readme.

**Comment by rohitsainiidsil** [comment]
Hello ,

Hope you are doing well !

Apologies for the same, there was some syntax error at my end. And pause
 Feature was not available in rest of the libraries.


Rohit Saini
Senior Software Developer
IDS Infotech Limited, India
I-8, Rajiv Gandhi Technology Park, Chandigarh. 160003
{+91) -172 5202903 |rohit.saini@idsil.com<mailto:rohit.saini@idsil.com> | www.idsil.com<http://www.idsil.com>

On 27-Aug-2020, at 3:48 PM, Kevin Leung <notifications@github.com<mailto:notifications@github.com>> wrote:



Closed #47<https://github.com/kevinresol/react-native-sound-recorder/issues/47>.
