### ISSUE TITLE
Hi, I am new to react-native, could anyone show me some examples on the use of this library in functional components? and how to save the filepath? thx!

### ISSUE THREAD

**Issue by wingchan1224** [kevinresol/react-native-sound-recorder#49]

**Comment by wingchan1224** [comment]
Hi Kelvin, any additional information needed ？so that I can post the issues
？thx🙏

在 2020年11月10日 週二 12:58，Kevin Leung <notifications@github.com> 寫道：

**Comment by kevinresol** [comment]
This issue list is for bug reporting but not for asking questions. Please try to follow the readme in order to use this library.

**Comment by wingchan1224** [comment]
Thx, but I have tried the Readme, but can't find the file that have
recoreded the audio

在 2020年11月10日 週二 20:12，Kevin Leung <notifications@github.com> 寫道：

**Comment by kevinresol** [comment]
The file path is resolved in the Promise returned by `stop()`

**Comment by wingchan1224** [comment]
Hi, Kelvin, sorry to bother you again,
I have followed the readme, and recorded the file, but I want to change the
filepath to other location, so that i can save the path in the backend
server, is it possible to do so? thx

Marco

Kevin Leung <notifications@github.com> 於 2020年11月10日 週二 下午10:10寫道：
