### ISSUE TITLE
When recording on iOS, in AMR audio format, start throws with empty object as error

### ISSUE THREAD

**Issue by tomsotte** [kevinresol/react-native-sound-recorder#50]
When recording on iOS 14, either simulator or physical device, using AMR audio format, `start` throws an empty object `{}` as error.
I've looked around and it seems the AMR audio format is [no longer being supported by AVPlayer](https://stackoverflow.com/questions/24103790/avaudioplayer-do-not-play-amr-files) so I suppose it's not available for recording as well..?

I've tried with both the iOS AMR audio format variants. Without specifying a format I can record correctly.

**Comment by kevinresol** [comment]
This library only aims to expose the available options. It is up to the OS to decide what is actually supported. So no action can be done here.
