### ISSUE TITLE
did you have exemple for “Options”？？

### ISSUE THREAD

**Issue by ibingdian** [kevinresol/react-native-sound-recorder#52]
did you have exemple for “Options”？？

----------------------------------------------------------------------------------------

Options:
iOS:

quality:Enum (Check out the constants prefixed with "QUALITY_")
format:Enum (Check out the constants prefixed with "FORMAT_")
bitRate:Int, default: not set (will fail on iPhone5 if set)
channels:Int (1 or 2), default: 1
sampleRate:Int default: 16000
Android:

source:Enum (Check out the constants prefixed with "SOURCE_")
format:Enum (Check out the constants prefixed with "FORMAT_")
encoder:Enum (Check out the constants prefixed with "ENCODER_")
channels:Int (1 or 2), default: 1
encodingBitRate:Int, default: 64000
sampleRate:Int default: 16000
Note that the above enums are platform-specific.

**Comment by kevinresol** [comment]
https://github.com/kevinresol/react-native-sound-recorder/pull/51#issuecomment-765059092

**Comment by rasheedk** [comment]
```
 SoundRecorder.start(
        SoundRecorder.PATH_CACHE + '/' + fileName + '.mp4',
        {
          quality: SoundRecorder.QUALITY_MAX,
          format : SoundRecorder.FORMAT_AAC_ADTS,

        }
      ).then(function () {
        console.log('started recording');
 
      });
```
