### ISSUE TITLE
`Cannot record audio at path`

### ISSUE THREAD

**Issue by KrisLau** [kevinresol/react-native-sound-recorder#60]
Not sure why but whenever i call 
```
await SoundRecorder.start(
  SoundRecorder.PATH_CACHE + '/intro.mp4',
) 
```
I get the error :
`Cannot record audio at path: file:///Users/newuser/Library/Developer/CoreSimulator/Devices/E478DE65-BB47-40D1-9458-0900DF9F8CB6/data/Containers/Data/Application/943974CE-A0DE-45ED-B7D3-12F73CBCF6E1/Library/Caches/intro.mp4`

**Comment by kevinresol** [comment]
Not sure if this will work on simulators at all. Did you try on real devices?

**Comment by kevinresol** [comment]
Also did you obtain the required permissions?

**Comment by KrisLau** [comment]
> Not sure if this will work on simulators at all. Did you try on real devices?

Nope I only tested on my simulator. I'll try it on a real device in a sec

> Also did you obtain the required permissions?

Yup I tried with and without

**Comment by Lordhacker756** [comment]
@KrisLau Any luck on the issue, I'm also facing the same problem, both in emulator and real device

**Comment by KrisLau** [comment]
@Lordhacker756 It works on a device

**Comment by Lordhacker756** [comment]
@KrisLau , Can you please guide me on why am I getting an empty error on starting the recording? 

![Screenshot 2023-04-28 at 2 00 59 AM](https://user-images.githubusercontent.com/70888328/234983997-58169f06-f140-4307-ad25-dc78c84c5169.png)
